name: Get weekly releases

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

defaults:
  run:
    working-directory: scripts/release-crawler

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Add weekly release notes
      CI_COMMIT_AUTHOR: Release Crawler
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache-dependency-path: scripts/release-crawler/go.sum
      - name: Run release crawler
        run: go run main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Configure git
        run: |
          git config user.name "Release Crawler"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create and push branch with git commands
        run: |
          BRANCH="add/related-projects-${{ steps.date.outputs.date }}"
          git checkout -b $BRANCH
          git add release-notes-html/*.html
          git add release-notes-md/*.md
          git commit --signoff -m "Add last weeks releated Project Updates"
          git push origin $BRANCH -f

      - name: Create Pull Request
        run: |
          BRANCH="add/related-projects-${{ steps.date.outputs.date }}"
          DATE="${{ steps.date.outputs.date }}"
          gh pr create \
            --title "add: last week related project releases" \
            --base "main" \
            --body "This PR is auto-generated. It adds the latest releases of the past week $DATE to the repository" \
            --label "add" \
            --label "automated pr" \
            --head "$BRANCH"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}