  on:
    schedule:
      - cron: '0 0 * * 1'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  permissions:
   contents: write # Allow to update the PR.
   pull-requests: write
   id-token: write

  defaults:
    run:
      working-directory: scripts/release-crawler
  jobs:
    build:
      runs-on: ubuntu-latest
      env:
        CI_COMMIT_MESSAGE: Add weekly release notes
        CI_COMMIT_AUTHOR: Release Crawler
      steps:
        - uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.21
        - run: go run main.go
        # Commit and push all changed files.
        - name: Get current date
          id: date
          run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Add last weeks releated Project Updates
            committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
            author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
            title: 'add: last week related project releases'
            body: |
              This PR is auto-generated.
              It adds the latest releases of the past week ${{ steps.date.outputs.date }} to the repository
            labels: add, automated pr
            branch: add/related-projects-${{ steps.date.outputs.date }}
            add-paths: |
               scripts/release-crawler/release-notes-html/*.html
               scripts/release-crawler/release-notes-md/*.md
            base: main
            signoff: true
            delete-branch: true
